######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 9 11:59:18 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . libraries qt_classes qt_classes/Screens
INCLUDEPATH += . qt_classes qt_classes/Screens libraries

# Input
HEADERS += Hash.h \
           libraries/json.hpp \
           qt_classes/LoginScreen.h \
           qt_classes/MainWindow.h \
           qt_classes/NavigationBar.h \
           qt_classes/Screen.h \
           qt_classes/Screens/AddChildScreen.h \
           qt_classes/Screens/CreateReportContainerScreen.h \
           qt_classes/Screens/CreateReportScreen.h \
           qt_classes/Screens/CreateUserScreen.h \
           qt_classes/Screens/GraphGraphicsScene.h \
           qt_classes/Screens/LoadReportScreen.h \
           qt_classes/Screens/NewAssessmentScreen.h \
           qt_classes/Screens/NewGroupDialog.h \
           qt_classes/Screens/ViewChildScreen.h
SOURCES += main.cpp \
           qt_classes/LoginScreen.cpp \
           qt_classes/MainWindow.cpp \
           qt_classes/NavigationBar.cpp \
           qt_classes/Screen.cpp \
           qt_classes/Screens/AddChildScreen.cpp \
           qt_classes/Screens/CreateReportContainerScreen.cpp \
           qt_classes/Screens/CreateReportScreen.cpp \
           qt_classes/Screens/CreateUserScreen.cpp \
           qt_classes/Screens/GraphGraphicsScene.cpp \
           qt_classes/Screens/LoadReportScreen.cpp \
           qt_classes/Screens/NewAssessmentScreen.cpp \
           qt_classes/Screens/NewGroupDialog.cpp \
           qt_classes/Screens/ViewChildScreen.cpp
