######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 13 16:29:22 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qt_classes qt_classes/Screens
INCLUDEPATH += . qt_classes qt_classes/Screens
QT += sql

# Input
HEADERS += Hash.h \
           qt_classes/LoginScreen.h \
           qt_classes/MainWindow.h \
           qt_classes/NavigationBar.h \
           qt_classes/Screen.h \
           qt_classes/Screens/AddChildScreen.h \
           qt_classes/Screens/CreateReportContainerScreen.h \
           qt_classes/Screens/CreateReportScreen.h \
           qt_classes/Screens/CreateUserScreen.h \
           qt_classes/Screens/GraphGraphicsScene.h \
           qt_classes/Screens/LoadReportScreen.h \
           qt_classes/Screens/NewAssessmentScreen.h \
           qt_classes/Screens/ViewChildScreen.h
SOURCES += main.cpp \
           qt_classes/LoginScreen.cpp \
           qt_classes/MainWindow.cpp \
           qt_classes/NavigationBar.cpp \
           qt_classes/Screen.cpp \
           qt_classes/Screens/AddChildScreen.cpp \
           qt_classes/Screens/CreateReportContainerScreen.cpp \
           qt_classes/Screens/CreateReportScreen.cpp \
           qt_classes/Screens/CreateUserScreen.cpp \
           qt_classes/Screens/GraphGraphicsScene.cpp \
           qt_classes/Screens/LoadReportScreen.cpp \
           qt_classes/Screens/NewAssessmentScreen.cpp \
           qt_classes/Screens/ViewChildScreen.cpp
